name: test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  rust-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      # Error build on warning (including clippy lints)
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: foundry-rs/foundry-toolchain@v1
      - run: anvil --fork-url 'https://eth.merkle.io' --fork-block-number 20927150 &
      - run: cargo clippy
      # node should be up before running tests
      - run: sleep 5
      - run: cargo test
